#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=fov
#SBATCH --nodes=8
##SBATCH --ntasks-per-node=16
#SBATCH --ntasks-per-node=1
#SBATCH --partition=riken
#SBATCH -q riken
#SBATCH --account=rbrcgeneral
#SBATCH -t 24:00:00

nodes=8
# nproc=128       # 128 = 8*16
nproc=8
MPIRUN='srun -N8 -n'${nproc}
# MPIRUN='srun --mpi=pmix -N8 -n'${nproc}

Nangles=36
madj=1

root="ckpoint_lat.4000"
runname="PVdagM_fov_Nang${Nangles}_madj${madj}_${SLURM_JOB_ID}"
outname="PVdagM_fov_Nang${Nangles}_madj${madj}_${SLURM_JOB_ID}"

homedir=/sdcc/u/poare
# inFile="/hpcgpfs01/work/lqcd/staging/RBC/32Ifine-rho0.124-tau4/702/${root}"
inFile="${homedir}/PETSc-Grid/ckpoint_lat.4000"

logDir="${homedir}/lqcd/multigrid/logs/${root}"
outDir="${homedir}/lqcd/multigrid/pseudospectra/fov/${root}/${runname}"
# outDir="/hpcgpfs01/work/lqcd/staging/RBC/${root}/ks_evecs/${outname}"

mkdir -p ${logDir}
mkdir -p ${outDir}

logs="${logDir}/${runname}.log"

cd ${homedir}/Grid/build/examples

# mpigrid=2.4.4.4
mpigrid=2.2.2.1
# vol=32.32.32.32
vol=16.16.16.32

# original aurora params
# PARAMS="--mpi ${mpigrid} --accelerator-threads 32 --device-mem 48000 --shm 2048 --shm-mpi 1 --grid ${vol}"

# ARGS="--StartingType ColdStart --StartingTrajectory  0 --Trajectories 1"
OPT='  --shm-mpi 0 --shm 16384  --comms-overlap --comms-concurrent --dslash-asm '
OPT2='  --auto-tune --verbose_add stout_performance --verbose_add cg_performance '

# export OMP_NUM_THREADS=4
# export OMP_PLACES=cores
# export OMP_PROC_BIND=close

export OMP_NUM_THREADS=64
export OMP_PLACES=0:64:1

module load openmpi

# echo "$MPIRUN ./Example_pvdagm_fov ${inFile} ${outDir} ${Nangles} ${madj} --mpi ${mpigrid} --grid ${vol} ${OPT} ${OPT2} > ${logs}"
$MPIRUN ./Example_pvdagm_fov ${inFile} ${outDir} ${Nangles} ${madj} --mpi ${mpigrid} --grid ${vol} ${OPT} ${OPT2} > ${logs}
