#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=gcr_coeffs
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=lqcd
#SBATCH --account=lqcdtest
#SBATCH -t 06:00:00

root=/sdcc/u/poare
logs=${root}/lqcd/multigrid/logs
cd ${root}/Grid/build/examples

# export OMP_NUM_THREADS=6

N=50
./Example_deflation_basis ${N} > ${logs}/gcr_coeffs_N${N}.out

# mpirun -np 4 Example_Laplacian > ${logs}/cfg${cfg}.txt
