#!/bin/bash

#ulimit -c unlimited

#SBATCH --job-name=mg
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
##SBATCH --partition=lqcd
##SBATCH --account=class-c-arnoldi
#SBATCH --partition=riken
#SBATCH -q riken
#SBATCH --account=rbrcgeneral
#SBATCH -t 24:00:00

nodes=1

# Nm=24
# Nk=8
# maxIter=1000
# Nstop=8

homedir=/sdcc/u/poare
# rf="EvalReSmall"

# eventually will use evecs stored in spectra for job 331989, for now use 330800

root="ckpoint_lat.4000"
runname="MG_PVdag_${SLURM_JOB_ID}"

# Job 333941 = first run of evec MG

homedir=/sdcc/u/poare
inFile="${homedir}/PETSc-Grid/ckpoint_lat.4000"

logDir="${homedir}/lqcd/multigrid/logs/${root}"
# outDir="${homedir}/lqcd/multigrid/spectra/${root}/${runname}"

mkdir -p ${logDir}
# mkdir -p ${outDir}

logs="${logDir}/${runname}.log"

cd ${homedir}/Grid/build/examples

# export OMP_NUM_THREADS=4
srun -N$nodes -n$nodes ./Example_pvdagm_svd > ${logs}
# srun -N$nodes -n$nodes /sdcc/u/poare/Grid/build/tests/debug/Test_general_coarse_pvdagm_svd_cg --grid 16.16.16.32 > ${logs}

