#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=free_field_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=prod
#SBATCH -t 6:00:00

set -x

# cd /data/wombat/users/mlwagman/mosaic
cd /home/poare/lqcd/mosaic

bash
module load openmpi/3.1.5
#module load qlua
# module load qlua/20200107
module load qlua/20200107-gpu1080
#module load qlua/20201002

EXE=qlua

gpu=true
# dwf=true
dwf=false

# whether to only compute current correlators, or to compute operator correlators as well
operators=true

test="free_field"
# test="gauge_transform"
# test="free_field_props"

home=/home/poare/lqcd/0nubb
logs=${home}/logs/tests/${test}_${SLURM_JOB_ID}
output=/data/d10b/users/poare/0nubb/output/tests/${test}_${SLURM_JOB_ID}

mkdir ${logs}
mkdir ${output}

parameters="jobid = ${SLURM_JOB_ID} dwf=${dwf} gpu=${gpu} operators=${operators}"
export OMP_NUM_THREADS=6

mpirun -np 4 $EXE -e "$parameters" ${home}/tests/${test}.qlua > ${logs}/0nubb_cfg${cfg}.txt
