#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=runtime_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=long
#SBATCH -t 72:00:00

set -x

# cd /home/poare/lqcd/mosaic
cd ./mosaic_copy

bash

# these need to be adjusted to the relevant paths
module load openmpi/3.1.5
module load qlua/20200107
EXE=qlua
home=/home/poare/lqcd/0nubb/tests/runtime_test

test="runtime_test"
logs=${home}/logs
output=${home}/output
cfgpath=${home}/configs/

# cfgpath="/data/d10b/ensembles/RBC/RBC_UKQCD_24_64/"
# cfgpath="'${home}'/configs/"
cfgbase="2+1f_24nt64_IWASAKI_b2.13_ls16_M1.8_ms0.04_mu0.005"
cfg=1200
parameters="jobid=${SLURM_JOB_ID} cfgpath='${cfgpath}' cfgbase='${cfgbase}' cfgnum=${cfg} out_folder='${output}'"
# parameters="jobid=${SLURM_JOB_ID} cfgnum=${cfg} out_folder='${output}'"
export OMP_NUM_THREADS=6

mpirun -np 4 $EXE -e "$parameters" ${home}/${test}.qlua > ${logs}/job${SLURM_JOB_ID}.txt
