#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=prop_gpu_test
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --partition=prod

set -x

cd /home/poare/lqcd/mosaic

bash
module load openmpi/3.1.5
# module load qlua
# module load qlua/20200107
module load qlua/20200107-gpu1080
# module load qlua/20200107-gpu2080
# module load qlua/gpu2080

EXE=qlua
#EXE=/opt/software/qlua-20200107-gpu2080

home=/home/poare/lqcd/qlua_scripts
logs=${home}/logs/gpu_test

export OMP_NUM_THREADS=6

mpirun -np 4 $EXE -e "jobid = ${SLURM_JOB_ID}" ${home}/gpu_test.qlua > ${logs}/job${SLURM_JOB_ID}.txt
