#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=npr_momfrac
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=prod4

set -x

# cd /data/wombat/users/mlwagman/mosaic
cd /home/poare/lqcd/mosaic

bash
module load openmpi/3.1.5
module load qlua/20200107-gpu1080

EXE=qlua

cfgpath="/data/d10b/ensembles/isoClover/"
cfgbase="cl3_16_48_b6p1_m0p2450"
gf=true
gpu=true

home=/home/poare/lqcd/npr_momfrac/testing
logs=${home}/logs/${cfgbase}_${SLURM_JOB_ID}
output=/data/d10b/users/poare/npr_momfrac/output

mkdir ${logs}
mkdir ${logs}/no_output
mkdir ${output}

parameters="jobid = ${SLURM_JOB_ID} cfgpath = '${cfgpath}' cfgbase = '${cfgbase}' gf=${gf} gpu=${gpu}"
export OMP_NUM_THREADS=6

cfg=200
mpirun -np 4 $EXE -e "$parameters cfgnum = ${cfg}" ${home}/free_field/zero_field_npr.qlua > ${logs}/cfg${cfg}.txt
