#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=vector_op_npr_3
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=a100r
#SBATCH -t 48:00:00

set -x

# cd /data/wombat/users/mlwagman/mosaic
cd /home/lqcd/poare/lqcd/mosaic

bash

# For the p-nodes on wombat
# module load openmpi
# module load openmpi/3.1.5
# module load qlua
# module load qlua/20201002
# module load qlua/20200107-gpu1080
# gpu=true

# For a-nodes on wombat
#module load PrgEnv-Wombat
#module load PrgEnv-Qlua
module load slurm/19.05.4.1

# Seems liek PrgEnv-Qlua has some issues
module load gcc/7.5.0
module load qlua/20201002
module load openmpi/3.1.5

gpu=false
EXE=qlua

home=/home/lqcd/poare/lqcd/0nubb/vector_ops
logs=${home}/logs/free_field_test

export OMP_NUM_THREADS=6

mpirun -np 4 $EXE -e "gpu=${gpu}" ${home}/free_field_test/vector_ops3.qlua > ${logs}/cfg_free_3.txt
