#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=npr_momfrac
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=devel

set -x

cd /data/wombat/users/mlwagman/mosaic

bash
module load openmpi
module load qlua

EXE=qlua

cfgpath="/data/d10b/ensembles/isoClover/"
cfgbase="cl3_16_48_b6p1_m0p2450"
gf=true
gpu=false

home=/home/poare/lqcd/npr_momfrac
tests=${home}/testing/logs
output=${home}/output/${cfgbase}_${SLURM_JOB_ID}

mkdir ${tests}
mkdir ${output}

parameters="jobid = ${SLURM_JOB_ID} cfgpath = '${cfgpath}' cfgbase = '${cfgbase}' gf=${gf} gpu=${gpu}"

cfg=200
mpirun -np 4 $EXE -e "$parameters cfgnum = ${cfg}" ${home}/npr_momfrac_test.qlua > ${tests}/job${SLURM_JOB_ID}.txt
