#!/bin/bash

##ulimit -c unlimited

#SBATCH --job-name=ex_npr_momfrac
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=long

set -x

cd /data/wombat/users/mlwagman/mosaic

bash
module load openmpi
module load qlua

EXE=qlua

home=/home/poare/lqcd/npr_momfrac/examples
logs=${home}/logs/job${SLURM_JOB_ID}

mkdir ${logs}

for cfg in `seq 200 10 250`
do
	mpirun -np 4 $EXE -e "cfgnum = ${cfg}" ${home}/example_npr.qlua > ${logs}/cfg${cfg}.txt
done
